/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.mistertea.html5animator.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Easing implements org.apache.thrift.TEnum {
  EASE_IN_LINEAR(0),
  EASE_IN_QUAD(1),
  EASE_OUT_QUAD(2),
  EASE_IN_OUT_QUAD(3),
  EASE_IN_CUBIC(4),
  EASE_OUT_CUBIC(5),
  EASE_IN_OUT_CUBIC(6);

  private final int value;

  private Easing(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Easing findByValue(int value) { 
    switch (value) {
      case 0:
        return EASE_IN_LINEAR;
      case 1:
        return EASE_IN_QUAD;
      case 2:
        return EASE_OUT_QUAD;
      case 3:
        return EASE_IN_OUT_QUAD;
      case 4:
        return EASE_IN_CUBIC;
      case 5:
        return EASE_OUT_CUBIC;
      case 6:
        return EASE_IN_OUT_CUBIC;
      default:
        return null;
    }
  }
}
